
package com.infotel.wsSoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProduitSOAPServiceService", targetNamespace = "http://wsSoap.infotel.com/", wsdlLocation = "http://localhost:8080/synthese-serveur-ejb-ws-equipe-1/ProduitSOAPService?wsdl")
public class ProduitSOAPServiceService
    extends Service
{

    private final static URL PRODUITSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUITSOAPSERVICESERVICE_EXCEPTION;
    private final static QName PRODUITSOAPSERVICESERVICE_QNAME = new QName("http://wsSoap.infotel.com/", "ProduitSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/synthese-serveur-ejb-ws-equipe-1/ProduitSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUITSOAPSERVICESERVICE_WSDL_LOCATION = url;
        PRODUITSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public ProduitSOAPServiceService() {
        super(__getWsdlLocation(), PRODUITSOAPSERVICESERVICE_QNAME);
    }

    public ProduitSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUITSOAPSERVICESERVICE_QNAME, features);
    }

    public ProduitSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, PRODUITSOAPSERVICESERVICE_QNAME);
    }

    public ProduitSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUITSOAPSERVICESERVICE_QNAME, features);
    }

    public ProduitSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProduitSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProduitSOAPService
     */
    @WebEndpoint(name = "ProduitSOAPServicePort")
    public ProduitSOAPService getProduitSOAPServicePort() {
        return super.getPort(new QName("http://wsSoap.infotel.com/", "ProduitSOAPServicePort"), ProduitSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProduitSOAPService
     */
    @WebEndpoint(name = "ProduitSOAPServicePort")
    public ProduitSOAPService getProduitSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsSoap.infotel.com/", "ProduitSOAPServicePort"), ProduitSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUITSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw PRODUITSOAPSERVICESERVICE_EXCEPTION;
        }
        return PRODUITSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
