
package com.infotel.wsSoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProduitSOAPService", targetNamespace = "http://wsSoap.infotel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProduitSOAPService {


    /**
     * 
     * @param date
     * @param prix
     * @param stock
     * @param nom
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterProdPerissable", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProdPerissable")
    @ResponseWrapper(localName = "ajouterProdPerissableResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProdPerissableResponse")
    public void ajouterProdPerissable(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "stock", targetNamespace = "")
        int stock,
        @WebParam(name = "prix", targetNamespace = "")
        double prix,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date);

    /**
     * 
     * @param idMagasin
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculPrixMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.CalculPrixMagasin")
    @ResponseWrapper(localName = "calculPrixMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.CalculPrixMagasinResponse")
    public double calculPrixMagasin(
        @WebParam(name = "idMagasin", targetNamespace = "")
        Long idMagasin);

    /**
     * 
     * @param idMagasin
     * @return
     *     returns ws.Magasin
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetMagasin")
    @ResponseWrapper(localName = "getMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetMagasinResponse")
    public Magasin getMagasin(
        @WebParam(name = "idMagasin", targetNamespace = "")
        long idMagasin);

    /**
     * 
     * @param date
     * @param prix
     * @param idMagasin
     * @param stock
     * @param nom
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterProduitPerissableMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProduitPerissableMagasin")
    @ResponseWrapper(localName = "ajouterProduitPerissableMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProduitPerissableMagasinResponse")
    public void ajouterProduitPerissableMagasin(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "stock", targetNamespace = "")
        int stock,
        @WebParam(name = "prix", targetNamespace = "")
        double prix,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "idMagasin", targetNamespace = "")
        Long idMagasin);

    /**
     * 
     * @param mode
     * @param prix
     * @param id
     * @param stock
     * @param nom
     * @return
     *     returns ws.Produit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierProdNonPerissable", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.ModifierProdNonPerissable")
    @ResponseWrapper(localName = "modifierProdNonPerissableResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.ModifierProdNonPerissableResponse")
    public Produit modifierProdNonPerissable(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "stock", targetNamespace = "")
        int stock,
        @WebParam(name = "prix", targetNamespace = "")
        double prix,
        @WebParam(name = "mode", targetNamespace = "")
        String mode);

    /**
     * 
     * @param date
     * @param prix
     * @param id
     * @param stock
     * @param nom
     * @return
     *     returns ws.Produit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierProdPerissable", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.ModifierProdPerissable")
    @ResponseWrapper(localName = "modifierProdPerissableResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.ModifierProdPerissableResponse")
    public Produit modifierProdPerissable(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "stock", targetNamespace = "")
        int stock,
        @WebParam(name = "prix", targetNamespace = "")
        double prix,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date);

    /**
     * 
     * @param idProduit
     * @return
     *     returns ws.Produit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduit", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetProduit")
    @ResponseWrapper(localName = "getProduitResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetProduitResponse")
    public Produit getProduit(
        @WebParam(name = "idProduit", targetNamespace = "")
        long idProduit);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Magasin>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMagasins", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetAllMagasins")
    @ResponseWrapper(localName = "getAllMagasinsResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetAllMagasinsResponse")
    public List<Magasin> getAllMagasins();

    /**
     * 
     * @return
     *     returns java.util.List<ws.Produit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProduits", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetAllProduits")
    @ResponseWrapper(localName = "getAllProduitsResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.GetAllProduitsResponse")
    public List<Produit> getAllProduits();

    /**
     * 
     * @param idProduit
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerProduit", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.SupprimerProduit")
    @ResponseWrapper(localName = "supprimerProduitResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.SupprimerProduitResponse")
    public void supprimerProduit(
        @WebParam(name = "idProduit", targetNamespace = "")
        long idProduit);

    /**
     * 
     * @param idMagasin
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.SupprimerMagasin")
    @ResponseWrapper(localName = "supprimerMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.SupprimerMagasinResponse")
    public void supprimerMagasin(
        @WebParam(name = "idMagasin", targetNamespace = "")
        long idMagasin);

    /**
     * 
     * @param code
     * @param prix
     * @param id
     * @param nom
     * @return
     *     returns ws.Magasin
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.ModifierMagasin")
    @ResponseWrapper(localName = "modifierMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.ModifierMagasinResponse")
    public Magasin modifierMagasin(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "code", targetNamespace = "")
        int code,
        @WebParam(name = "prix", targetNamespace = "")
        double prix);

    /**
     * 
     * @param mode
     * @param prix
     * @param stock
     * @param nom
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterProdNonPerissable", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProdNonPerissable")
    @ResponseWrapper(localName = "ajouterProdNonPerissableResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProdNonPerissableResponse")
    public void ajouterProdNonPerissable(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "stock", targetNamespace = "")
        int stock,
        @WebParam(name = "prix", targetNamespace = "")
        double prix,
        @WebParam(name = "mode", targetNamespace = "")
        String mode);

    /**
     * 
     * @param mode
     * @param prix
     * @param idMagasin
     * @param stock
     * @param nom
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterProduitNonPerissableMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProduitNonPerissableMagasin")
    @ResponseWrapper(localName = "ajouterProduitNonPerissableMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterProduitNonPerissableMagasinResponse")
    public void ajouterProduitNonPerissableMagasin(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "stock", targetNamespace = "")
        int stock,
        @WebParam(name = "prix", targetNamespace = "")
        double prix,
        @WebParam(name = "mode", targetNamespace = "")
        String mode,
        @WebParam(name = "idMagasin", targetNamespace = "")
        Long idMagasin);

    /**
     * 
     * @param code
     * @param prix
     * @param nom
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterMagasin", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterMagasin")
    @ResponseWrapper(localName = "ajouterMagasinResponse", targetNamespace = "http://wsSoap.infotel.com/", className = "ws.AjouterMagasinResponse")
    public void ajouterMagasin(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "code", targetNamespace = "")
        int code,
        @WebParam(name = "prix", targetNamespace = "")
        double prix);

}
